services:
  - type: web
    name: jobportal-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: DB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRE
        value: 15m
      - key: ACCESS_TOKEN_COOKIE_EXPIRE_MINUTES
        value: 15
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30
      - key: COOKIE_EXPIRE
        value: 7
      - key: COOKIE_SAME_SITE
        value: none
      - key: COOKIE_SECURE
        value: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: ADZUNA_COUNTRY
        value: in
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
